version: 2

jobs:
  build:
    docker:
      - image: swift:4.2.1
    steps:
      - checkout
      - run: swift build
  test:
    docker:
      - image: swift:4.2.1
    steps:
      - checkout
      - run: swift test
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test
